=== pswsm/pswsm-repo/markup/xml/pt1/activitat1/xarxa.dtd
<!ELEMENT xarxa (domini, ordinadors+)>
<!ELEMENT domini (#PCDATA)>
<!ELEMENT ordinadors (pc*)>
<!ELEMENT pc (nom, configuracio, sistemaOperatiu)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT configuracio (#PCDATA)>
<!ELEMENT sistemaOperatiu (#PCDATA)>

=== pswsm/pswsm-repo/markup/xml/pt1/activitat1/xarxa.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xarxa SYSTEM "xarxa.dtd">
<xarxa>
  <domini>institut.cat</domini>
  <ordinadors>
    <pc>
      <nom>A</nom>
      <configuracio>dhcp</configuracio>
      <sistemaOperatiu>Ubuntu Lucid</sistemaOperatiu>
    </pc>
    <pc>
      <nom>B</nom>
      <configuracio>dhcp</configuracio>
      <sistemaOperatiu>Windows 7</sistemaOperatiu>
    </pc>
    <pc>
      <nom>B</nom>
      <configuracio>dhcp</configuracio>
      <sistemaOperatiu>Fedora 16</sistemaOperatiu>
    </pc>
  </ordinadors>
  <ordinadors>
    <pc>
      <nom>Servidor</nom>
      <configuracio>IP Fixa</configuracio>
      <sistemaOperatiu>Ubuntu Server</sistemaOperatiu>
    </pc>
    <pc>
      <nom>D</nom>
      <configuracio>dhcp</configuracio>
      <sistemaOperatiu>Windows XP</sistemaOperatiu>
    </pc>
  </ordinadors>
</xarxa>
