=== pswsm/pswsm-repo/markup/xml/pt1/activitat2/agenda.dtd
<!ELEMENT agenda (persona)*>
<!ELEMENT persona (nombre, email*, relacion*, fijo*, movil*)>
<!ATTLIST persona genero (hombre|mujer) #IMPLIED>
<!ATTLIST persona id CDATA #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT relacion (#PCDATA)>
<!ATTLIST relacion amigo_de CDATA #REQUIRED>
<!ELEMENT fijo EMPTY>
<!ELEMENT movil EMPTY>

=== pswsm/pswsm-repo/markup/xml/pt1/activitat2/activitat2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agenda SYSTEM "agenda.dtd">
<agenda>
  <persona genero="hombre" id="xaviergutierrez">
    <nombre>Xavier Gutierrez</nombre>
    <email>xaviergutierrez1@gmail.com</email>
    <email>xav.gut@gmail.com</email>
    <relacion amigo_de="elisamoreno"></relacion>
    <fijo/>
  </persona>
    <persona genero="mujer" id="elisamoreno">
    <nombre>Elisa Moreno</nombre>
    <email>Elisamor@gmail.com</email>
    <movil/>
  </persona>
    <persona id="carlagutierrez">
    <nombre>Carla Gutierrez</nombre>
    <relacion amigo_de="xaviergutierrez"></relacion>
    <fijo></fijo>
  </persona>
</agenda>
