=== pswsm/pswsm-repo/markup/xml/pt1/activitat3/the.dtd
<!ELEMENT juego (personaje+,escenario,musica)>
<!ELEMENT personaje (nombre,vidas,armas*,herramientas,superpoder?)>
<!ELEMENT escenario ((planeta|pais),nombre_lugar,coordenadas)>
<!ELEMENT musica (nombre_cancion,genero)*>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT vidas (#PCDATA)>
<!ELEMENT armas (#PCDATA)>
<!ELEMENT herramientas (#PCDATA)>
<!ELEMENT superpoder EMPTY>
<!ELEMENT planeta (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT nombre_lugar (#PCDATA)>
<!ELEMENT coordenadas (x,y,z)>
<!ELEMENT x (#PCDATA)>
<!ELEMENT y (#PCDATA)>
<!ELEMENT z (#PCDATA)>
<!ELEMENT nombre_cancion (#PCDATA)>
<!ELEMENT genero (#PCDATA)>
<!ATTLIST juego nombre CDATA #REQUIRED>
<!ATTLIST juego dificultad (baja|media|alta) #REQUIRED>
<!ATTLIST personaje alien (si|no) "no">
<!ATTLIST superpoder descripcion CDATA #IMPLIED>

=== pswsm/pswsm-repo/markup/xml/pt1/activitat3/2nvalid.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE juego SYSTEM "the.dtd">

<juego nombre="collblanc" dificultad="baja">
  <escenario>
    <pais>Catalunya</pais>
    <nombre_lugar>L'Hospitalet de Llobregat</nombre_lugar>
    <coordenadas>
      <x>41</x>
      <y>35</y>
      <z>67+</z>
    </coordenadas>
  </escenario>
  <musica>
    <nombre_cancion>PDA</nombre_cancion>
    <genero>Trap Catala</genero>
  </musica>
</juego>

=== pswsm/pswsm-repo/markup/xml/pt1/activitat3/5valid.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE juego SYSTEM "the.dtd">

<juego nombre="collblanc" dificultad="baja">
  <personaje alien="no">
    <nombre>pswsm</nombre>
    <vidas>∞</vidas>
    <armas>FGC-9</armas>
    <armas>Vector .45 ACP</armas>
    <armas>D-50</armas>
    <herramientas>godmode</herramientas>
    <superpoder/>
    <superpoder/>
  </personaje>
  <personaje alien="no">
    <nombre>not me</nombre>
    <vidas>1</vidas>
    <herramientas>múscul</herramientas>
  </personaje>
  <escenario>
    <pais>Catalunya</pais>
    <nombre_lugar>L'Hospitalet de Llobregat</nombre_lugar>
    <coordenadas>
      <x>41</x>
      <y>35</y>
      <z>67+</z>
    </coordenadas>
  </escenario>
  <musica>
    <nombre_cancion>PDA</nombre_cancion>
    <genero>Trap Catala</genero>
  </musica>
</juego>
